Script to generate docs for forc commands + examples (#1047)
* Update book with forc commands

* Fix SUMMARY.md errors when merging

* Move all command pages under /commands dir

* Fix broken link to commands/index.md

Co-authored-by: John Adler <adlerjohn@users.noreply.github.com>

* Prelim version of a script

* Generation of all command pages based on forc --help

* Clean up main.rs

* Re-generate docs with script

* Fix test_format_option_line test

* Re-build docs without comma after options

* Remove extra printlns

* Add logic to insert examples

* Re-generate docs with examples

* generate forc_deploy.md

* Rename command to write-docs

* Fix dependencies ordering within Cargo.toml

* Move more constants

* added dry-run for checking

* Fix clippy checks

* Rework some error handling when doing dry run

* Integrate mdbook build and forc-documenter checks into ci

* Test a hack for checking errors in mdbook

* Add uses checkout

* Fix dashes

* Fix uses/run in single step

* Try if grep

* fix yaml syntax

* fix yaml syntax, for real

* Fix running forc-documenter from project root

* Try cat for github action

* Fix Cargo.lock

* add install forc to forc-documenter job

* Missed out args line

* Trim newline from start and end of md files

* Fix index header duplicate and add trim() to result

* Fix dry-run behaviour for index

* Remove all commands before starting write-docs to remove outdated commands

* Re-generate

* Remove outdated forc commands from SUMMARY.md

* Extract code from main.rs into helpers.rs

* Handle updating SUMMARY.md as well

* Fix cargo clippy stuff

* Add readme for forc-documenter

* Add version message

* Re-generate docs

* Re-generate docs

* Revert unintended formatting changes

* Fix typo in forc-documenter README.md

* Rename _command to command

* Refactor code within script

* Separate check functions from helpers module

* More refactoring into components

* Re-arrange functions in main

* Add hello world test as a code block instead of a link

* Add docs for forc plugins

Co-authored-by: John Adler <adlerjohn@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -78,6 +78,25 @@ jobs:
           command: run
           args: --bin build-all-examples
 
+  build-mdbook:
+    needs: cancel-previous-runs
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Run mdbook build
+        uses: peaceiris/actions-mdbook@v1
+        with:
+          mdbook-version: '0.4.7'
+      - name: Emit logs to tmp.txt, fail if build logs contain 'ERROR'
+        run: |
+          mdbook build docs &> tmp.txt
+          if cat tmp.txt | grep 'ERROR'
+          then
+            rm tmp.txt && exit 1
+          else
+            rm tmp.txt && exit 0
+          fi
+
   cargo-build-workspace:
     needs: cancel-previous-runs
     runs-on: ubuntu-latest
@@ -205,6 +224,27 @@ jobs:
         uses: actions-rs/cargo@v1
         with:
           command: test
+
+  forc-documenter-dry-run:
+    needs: cancel-previous-runs
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+      - uses: Swatinem/rust-cache@v1
+      - name: Install Forc
+        uses: actions-rs/cargo@v1
+        with:
+          command: install
+          args: --debug --path ./forc
+      - name: Run forc-documenter in dry run mode
+        uses: actions-rs/cargo@v1
+        with:
+          command: run
+          args: --bin forc-documenter write-docs --dry-run
 
   cargo-unused-deps-check:
     needs: cancel-previous-runs
