Try if grep

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -87,11 +87,15 @@ jobs:
         uses: peaceiris/actions-mdbook@v1
         with:
           mdbook-version: '0.4.7'
-      - name: Emit logs to tmp.txt
-        run: mdbook build docs &> tmp.txt
-      - name: Fail if build logs contain "ERROR"
-        if: ${{ [ -s tmp.txt ] }}
-        run: rm tmp.txt && exit 1
+      - name: Emit logs to tmp.txt, fail if build logs contain 'ERROR'
+        run: |
+        mdbook build docs &> tmp.txt \
+        if grep '[ERROR]' tmp.txt > /dev/null
+        then
+          rm tmp.txt && exit 1
+        else
+          rm tmp.txt && exit 0
+        fi
 
   cargo-build-workspace:
     needs: cancel-previous-runs
